### PR TITLE
Adds appveyor build

### PR DESCRIPTION
**Pull request by brianium**

### CODE REVIEW

**Comment by brianium** [comment]
@ezzatron This creates a working appveyor build. If we get this merged we can close/reopen the other PRS to get greens across the board.

If you look at the appveyor build output, there are definitely some encoding issues with the checkmarks in spec report, but we can maybe address that later?

**Comment by brianium** [comment]
screen shot 2016-11-26 at 10 31 22 am

**Comment by ezzatron** [comment]
Yeah, it might be worth seeing if these issues actually happen when running under Windows. We have some people at work running Windows, I'll try to pester them today. If it's only happening on AppVeyor, then I think it's no biggie.

**Comment by ezzatron** [comment]
Yeah there's definitely still some issues running under Windows. I got a workmate to give it a go, and the output looked a bit like this:

```

  AbstractBaseReporter
    ->symbol()
      when in a windows environment
        ¹ should return ASCII char 251 for check symbol
    ->color()
      when in a windows environment
        ←[32m¹←[39m ←[90mshould add escape sequences if ansicon is enabled←[0m
      when in a tty terminal
        ←[31m1) should set the PERIDOT_TTY environment variable←[39m
        ←[32m¹←[39m ←[90mshould write colors if the PERIDOT_TTY environment variable is present←[0m
        ←[32m¹←[39m ←[90mshould not write colors when output is not a stream output←[0m

  AnonymousReporter
    ←[32m¹←[39m ←[90mshould call the init function passed in←[0m

  Application
    during construction
      ←[32m¹←[39m ←[90mshould emit peridot.start with environment and self←[0m
    ->loadDsl()
      ←[32m¹←[39m ←[90mshould include a file if it exists←[0m
      ←[32m¹←[39m ←[90mshould not include the same dsl twice←[0m
    ->getCommandName()
      ←[32m¹←[39m ←[90mshould return "peridot"←[0m
    ->getInput()
      ←[32m¹←[39m ←[90mshould return an input←[0m
    ->getEnvironment()
      ←[32m¹←[39m ←[90mshould return the Environment used by the application←[0m
    configuration accessors
      ←[32m¹←[39m ←[90mshould allow access to configuration←[0m
    runner accessors
      ←[32m¹←[39m ←[90mshould allow access to runner←[0m
      when getting Runner
        ←[32m¹←[39m ←[90mshould return a default runner if none set←[0m

  CliOptionParser
    ->parse()
      ←[32m¹←[39m ←[90mshould return values associated with search←[0m
      ←[32m¹←[39m ←[90mshould return an empty array if no matches←[0m

  Command
    loader accessors
      ←[32m¹←[39m ←[90mshould allow setting and getting of loader←[0m
      ←[32m¹←[39m ←[90mshould allow getting a default loader←[0m
    runner accessors
      ←[32m¹←[39m ←[90mshould allow setting and getting of the runner←[0m
    ->getSynopsis()
      ←[32m¹←[39m ←[90mshould return a simplified synopsis←[0m
    ->run()
      ←[32m¹←[39m ←[90mshould emit an execute event←[0m
      ←[32m¹←[39m ←[90mshould emit a reporters event←[0m
      when using the --reporters option
        ←[32m¹←[39m ←[90mshould list reporters←[0m
      when passing a reporter name
        ←[32m¹←[39m ←[90mshould set the reporter name on the configuration object←[0m
      ←[32m¹←[39m ←[90mshould emit a load event←[0m
      when there are failing tests
        ←[32m¹←[39m ←[90mshould return an exit code←[0m

  ConfigurationReader
    ->read()
      ←[32m¹←[39m ←[90mshould return configuration from InputInterface←[0m
      ←[32m¹←[39m ←[90mshould throw an exception if configuration is specified but does not exist←[0m
    ::readInput()
      ←[32m¹←[39m ←[90mshould read input←[0m

  Configuration
    reporter accessors
      ←[32m¹←[39m ←[90mshould allow getting and setting of a reporter name←[0m
    ->setConfigurationFile()
      ←[32m¹←[39m ←[90mshould check current working directory with file name←[0m
      ←[32m¹←[39m ←[90mit should throw an exception if the file does not exist←[0m
    dsl accessors
      ←[32m¹←[39m ←[90mshould allow getting and setting of a dsl path←[0m
    setters
      ←[32m¹←[39m ←[90mshould write corresponding peridot environment variables←[0m
    ->enableColorsExplicit()
      ←[32m¹←[39m ←[90mshould enable colors when explicit is set←[0m

  Context
    ->addSuite()
      ←[32m¹←[39m ←[90mshould allow nesting of suites←[0m
      ←[32m¹←[39m ←[90mshould allow sibling suites←[0m
      ←[32m¹←[39m ←[90mshould set pending if value is not null←[0m
      ←[32m¹←[39m ←[90mshould ignore pending if value is null←[0m
      ←[32m¹←[39m ←[90mshould execute a suites bound definition←[0m
    ->addTest()
      ←[32m¹←[39m ←[90mshould set pending status if value is not null←[0m
      ←[32m¹←[39m ←[90mshould ignore pending status if value is null←[0m
      ←[32m¹←[39m ←[90mshould set pending to true if definition is null←[0m
      ←[32m¹←[39m ←[90mshould increase size of root suite←[0m
    ->setFile()
      ←[32m¹←[39m ←[90mshould set the file on suites added via context←[0m
      ←[32m¹←[39m ←[90mshould set the file on tests added via context←[0m
    ->clear()
      ←[32m¹←[39m ←[90mshould reset loaded suites←[0m
    ->addSetupFunction()
      ←[32m¹←[39m ←[90mshould register an beforeEach callback on the current suite←[0m
    ->addTearDownFunction()
      ←[32m¹←[39m ←[90mshould register an afterEach callback on the current suite←[0m
    ::getInstance()
      ←[32m¹←[39m ←[90mshould return a singleton instance of Context←[0m

  Environment
    ->getDefinition()
      ←[32m¹←[39m ←[90mshould return the input definition←[0m
    ->load()
      ←[32m¹←[39m ←[90mshould return true when it includes the config file←[0m
      ←[32m¹←[39m ←[90mshould return true when it includes the default config file←[0m
      ←[32m¹←[39m ←[90mshould return false when it cant include the config file←[0m

  InputDefinition
    ->argument()
      ←[32m¹←[39m ←[90mshould add an argument to the definition←[0m
    ->option()
      ←[32m¹←[39m ←[90mshould add an option to the definition←[0m

  ReporterFactory
    ->create()
      using a valid reporter name
        ←[32m¹←[39m ←[90mshould return an instance of the named reporter←[0m
        ←[32m¹←[39m ←[90mshould return an anonymous reporter if callable used←[0m
      using a valid name with an invalid factory
        ←[32m¹←[39m ←[90mshould throw an exception←[0m
      using an invalid name
        ←[32m¹←[39m ←[90mshould throw an exception←[0m
    ->getReporters()
      ←[32m¹←[39m ←[90mshould return an array of reporter information←[0m
    ->register()
      using a class
        ←[32m¹←[39m ←[90mshould add named reporter to list of reporters←[0m

  Runner
    running a single suite
      ←[32m¹←[39m ←[90mshould run a given suite←[0m
    running a suite with children
      ←[32m¹←[39m ←[90mshould run a suite with children←[0m
    ->run()
      ←[32m¹←[39m ←[90mshould emit a start event when the runner starts←[0m
      ←[32m¹←[39m ←[90mshould emit an end event with run time when the runner ends←[0m
      ←[32m¹←[39m ←[90mshould emit a fail event when a spec fails←[0m
      ←[32m¹←[39m ←[90mshould emit a pass event when a spec passes←[0m
      ←[32m¹←[39m ←[90mshould emit a pending event when a spec is pending←[0m
      ←[32m¹←[39m ←[90mshould emit a suite:start event every time a suite starts←[0m
      ←[32m¹←[39m ←[90mshould emit a suite:end every time a suite ends←[0m
      when configured to bail on failure
        ←[32m¹←[39m ←[90mshould stop running on failure←[0m

  SpecReporter
    when test.failed is emitted
      ←[32m¹←[39m ←[90mshould include an error number and the test description←[0m
    when test.pending is emitted
      ←[32m¹←[39m ←[90mshould include an error number and the test description←[0m
    ->color()
      when colors are disabled
        ←[32m¹←[39m ←[90mshould return plain text←[0m
    ->footer()
      ←[32m¹←[39m ←[90mshould output success text←[0m
      ←[32m¹←[39m ←[90mshould output time←[0m
      ←[32m¹←[39m ←[90mshould output failure text←[0m
      ←[32m¹←[39m ←[90mshould output pending count←[0m
      ←[32m¹←[39m ←[90mshould display exception stacks and messages←[0m

  Suite
    ->run()
      ←[32m¹←[39m ←[90mshould run multiple tests←[0m
      ←[32m¹←[39m ←[90mshould pass setup functions to tests←[0m
      ←[32m¹←[39m ←[90mshould pass child scopes to tests←[0m
      ←[32m¹←[39m ←[90mshould pass teardown functions to tests←[0m
      ←[32m¹←[39m ←[90mshould set pending status on tests if not null←[0m
      ←[32m¹←[39m ←[90mshould emit a suite.start event←[0m
      ←[32m¹←[39m ←[90mshould emit a suite.end event←[0m
      ←[32m¹←[39m ←[90mshould stop when a halt event is received←[0m
    ->addTest()
      ←[32m¹←[39m ←[90mshould set parent property on child test←[0m
    ->setTests()
      ←[32m¹←[39m ←[90mshould set the tests to the passed in value←[0m
    file accessors
      ←[32m¹←[39m ←[90mshould allow access to the file property←[0m
    ->define()
      ←[32m¹←[39m ←[90mshould call the suite definition with definition arguments←[0m
      ←[32m¹←[39m ←[90mshould emit a suite.define event←[0m

  SuiteLoader
    ->getTests()
      ←[32m¹←[39m ←[90mshould return file paths matching *.spec.php recursively←[0m
      ←[32m¹←[39m ←[90mshould return single file if it exists←[0m
      ←[32m¹←[39m ←[90mshould throw exception if path not found←[0m
      when search path contains a trailing slash
        ←[32m¹←[39m ←[90mshould not include multiple directory separators←[0m
    ->load()
      ←[32m¹←[39m ←[90mshould include files matching the pattern←[0m
      ←[31m2) should set the context file path←[39m

  TestResult
    ←[32m¹←[39m ←[90mshould return the number of tests run←[0m
    ←[32m¹←[39m ←[90mshould return the number of tests failed←[0m
    ->startTest()
      ←[32m¹←[39m ←[90mshould increment the test count←[0m
      ←[32m¹←[39m ←[90mshould fire a test.start event←[0m
    ->endTest()
      ←[32m¹←[39m ←[90mshould fire a test.end event←[0m
    ->failTest()
      ←[32m¹←[39m ←[90mshould emit a test.failed event←[0m
    ->passTest()
      ←[32m¹←[39m ←[90mshould emit a test.passed event←[0m
    ->pendTest()
      ←[32m¹←[39m ←[90mshould emit a test.pending event←[0m
    pending test accessors
      ←[32m¹←[39m ←[90mshould allow access to the total number of pending tests←[0m
    failure accessors
      ←[32m¹←[39m ←[90mshould allow access to the total number of failures←[0m
    test count accessors
      ←[32m¹←[39m ←[90mshould allow access to the total number of tests←[0m

  Test
    when constructed with null definition
      ←[32m¹←[39m ←[90mit should default to a pending state←[0m
    ->run()
      ←[32m¹←[39m ←[90mshould run←[0m
      ←[32m¹←[39m ←[90mshould run setup functions←[0m
      ←[32m¹←[39m ←[90mshould run teardown functions←[0m
      ←[32m¹←[39m ←[90mshould modify a passed in result←[0m
      ←[32m¹←[39m ←[90mshould add failed results to result←[0m
      ←[32m¹←[39m ←[90mshould add failed results to result on error←[0m
      ←[32m¹←[39m ←[90mshould ignore errors that are excluded by error reporting←[0m
      ←[32m¹←[39m ←[90mshould ignore errors that are excluded by the error control operator←[0m
      ←[32m¹←[39m ←[90mshould add failed results to result on engine error←[0m
      ←[32m¹←[39m ←[90mshould add pending results to result←[0m
      ←[32m¹←[39m ←[90mshould skip test if set up fails←[0m
      when test is pending
        ←[32m¹←[39m ←[90mshould not execute←[0m
      when definition arguments have been given
        ←[32m¹←[39m ←[90mshould pass arguments to test←[0m
      when running setup functions
        ←[32m¹←[39m ←[90mshould run setup functions in order←[0m
        ←[32m¹←[39m ←[90mshould run parent setup functions first←[0m
      when running tear down functions
        ←[32m¹←[39m ←[90mshould run child tear down functions first←[0m
        ←[32m¹←[39m ←[90mshould run tear down functions even if spec fails←[0m
        ←[32m¹←[39m ←[90mshould run tear down functions even if setup fails←[0m
        ←[32m¹←[39m ←[90mshould continue if tear down fails←[0m
        ←[32m¹←[39m ←[90mshould continue if tear down fails with an engine error←[0m
        ←[32m¹←[39m ←[90mshould not result in a pass and fail if tear down fails←[0m
    ->getTitle()
      ←[32m¹←[39m ←[90mshould return the full text for a spec including parents←[0m
    ->setPending()
      ←[32m¹←[39m ←[90mshould set the pending status←[0m
    ->setScope()
      ←[32m¹←[39m ←[90mshould set the scope of the test←[0m
    ->setParent()
      ←[32m¹←[39m ←[90mshould bind the parent scope to the child←[0m
    file accessors
      ←[32m¹←[39m ←[90mshould allow access to the file property←[0m

←[32m
  136 passing←[39m←[90m (404 ms)←[0m
←[31m  2 failing←[39m

  1) AbstractBaseReporter ->color() when in a tty terminal should set the PERIDOT_TTY environment variable:
←[31m     peridot tty environment variable should have been set←[39m
←[90m      #0 [internal function]: Peridot\Console\Application->{closure}('C:\\Users\\jimbo\\...', 56, '', 'peridot tty
env...')
      #1 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\specs\abstract-base-reporter.spec.php(56): asser
t(false, 'peridot tty env...')
      #2 [internal function]: Peridot\Core\Scope->{closure}()
      #3 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Core\Test.php(61): call_user_func_array(Obje
ct(Closure), Array)
      #4 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Core\Test.php(46): Peridot\Core\Test->execut
eTest(Object(Peridot\Core\TestResult))
      #5 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Core\Suite.php(112): Peridot\Core\Test->run(
Object(Peridot\Core\TestResult))
      #6 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Core\Suite.php(83): Peridot\Core\Suite->runT
est(Object(Peridot\Core\Test), Object(Peridot\Core\TestResult))
      #7 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Core\Suite.php(112): Peridot\Core\Suite->run
(Object(Peridot\Core\TestResult))
      #8 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Core\Suite.php(83): Peridot\Core\Suite->runT
est(Object(Peridot\Core\Suite), Object(Peridot\Core\TestResult))
      #9 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Core\Suite.php(112): Peridot\Core\Suite->run
(Object(Peridot\Core\TestResult))
      #10 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Core\Suite.php(83): Peridot\Core\Suite->run
Test(Object(Peridot\Core\Suite), Object(Peridot\Core\TestResult))
      #11 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Core\Suite.php(112): Peridot\Core\Suite->ru
n(Object(Peridot\Core\TestResult))
      #12 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Core\Suite.php(83): Peridot\Core\Suite->run
Test(Object(Peridot\Core\Suite), Object(Peridot\Core\TestResult))
      #13 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Runner\Runner.php(57): Peridot\Core\Suite->
run(Object(Peridot\Core\TestResult))
      #14 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Console\Command.php(176): Peridot\Runner\Ru
nner->run(Object(Peridot\Core\TestResult))
      #15 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Console\Command.php(149): Peridot\Console\C
ommand->getResult()
      #16 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\vendor\symfony\console\Command\Command.php(254)
: Peridot\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\O
utput\ConsoleOutput))
      #17 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\vendor\symfony\console\Application.php(820): Sy
mfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component
\Console\Output\ConsoleOutput))
      #18 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\vendor\symfony\console\Application.php(187): Sy
mfony\Component\Console\Application->doRunCommand(Object(Peridot\Console\Command), Object(Symfony\Component\Console\Inpu
t\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #19 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Console\Application.php(84): Symfony\Compon
ent\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Outpu
t\ConsoleOutput))
      #20 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\vendor\symfony\console\Application.php(118): Pe
ridot\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Out
put\ConsoleOutput))
      #21 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Console\Application.php(63): Symfony\Compon
ent\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\
ConsoleOutput))
      #22 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\bin\peridot(45): Peridot\Console\Application->r
un()
      #23 {main}←[0m
  2) SuiteLoader ->load() should set the context file path:
←[31m     expected C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\fixtures\test2.spec.php, got C:\Users\
jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\fixtures/test2.spec.php←[39m
←[90m      #0 [internal function]: Peridot\Console\Application->{closure}('C:\\Users\\jimbo\\...', 64, '', 'expected C:\
\Use...')
      #1 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\specs\suiteloader.spec.php(64): assert(false, 'e
xpected C:\\Use...')
      #2 [internal function]: Peridot\Core\Scope->{closure}()
      #3 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Core\Test.php(61): call_user_func_array(Obje
ct(Closure), Array)
      #4 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Core\Test.php(46): Peridot\Core\Test->execut
eTest(Object(Peridot\Core\TestResult))
      #5 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Core\Suite.php(112): Peridot\Core\Test->run(
Object(Peridot\Core\TestResult))
      #6 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Core\Suite.php(83): Peridot\Core\Suite->runT
est(Object(Peridot\Core\Test), Object(Peridot\Core\TestResult))
      #7 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Core\Suite.php(112): Peridot\Core\Suite->run
(Object(Peridot\Core\TestResult))
      #8 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Core\Suite.php(83): Peridot\Core\Suite->runT
est(Object(Peridot\Core\Suite), Object(Peridot\Core\TestResult))
      #9 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Core\Suite.php(112): Peridot\Core\Suite->run
(Object(Peridot\Core\TestResult))
      #10 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Core\Suite.php(83): Peridot\Core\Suite->run
Test(Object(Peridot\Core\Suite), Object(Peridot\Core\TestResult))
      #11 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Runner\Runner.php(57): Peridot\Core\Suite->
run(Object(Peridot\Core\TestResult))
      #12 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Console\Command.php(176): Peridot\Runner\Ru
nner->run(Object(Peridot\Core\TestResult))
      #13 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Console\Command.php(149): Peridot\Console\C
ommand->getResult()
      #14 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\vendor\symfony\console\Command\Command.php(254)
: Peridot\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\O
utput\ConsoleOutput))
      #15 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\vendor\symfony\console\Application.php(820): Sy
mfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component
\Console\Output\ConsoleOutput))
      #16 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\vendor\symfony\console\Application.php(187): Sy
mfony\Component\Console\Application->doRunCommand(Object(Peridot\Console\Command), Object(Symfony\Component\Console\Inpu
t\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #17 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Console\Application.php(84): Symfony\Compon
ent\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Outpu
t\ConsoleOutput))
      #18 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\vendor\symfony\console\Application.php(118): Pe
ridot\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Out
put\ConsoleOutput))
      #19 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\src\Console\Application.php(63): Symfony\Compon
ent\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\
ConsoleOutput))
      #20 C:\Users\jimbo\Downloads\php-7.0.13-nts-Win32-VC14-x64\peridot\bin\peridot(45): Peridot\Console\Application->r
un()
      #21 {main}←[0m
```

I'm still happy for this to get merged for now. I'll open a separate issue for fixing tick/color output under Windows.

**Comment by ezzatron** [comment]
@brianium Are you happy for me to rebase & merge this PR and #191?

**Comment by brianium** [comment]
I think so man. Thanks!

**Comment by ezzatron** [comment]
Manually merged in [#7c7e9fb](https://github.com/peridot-php/peridot/commit/7c7e9fb).

**Pull request closed without merging**
