### PR TITLE
[Bug] usage of incorrect "set_error_handler" interface

### PR DESCRIPTION
**Pull request by YuraLukashik**
It fails with the only error code.
[http://php.net/manual/ru/function.set-error-handler.php](http://php.net/manual/ru/function.set-error-handler.php)

### CODE REVIEW

**Comment by ezzatron** [comment]
Thanks for the PR! This should be fine to merge, and I'll try to include it in the next release.

So that I can include some extra tests, would you be able to paste the error handler code that you are using when this error occurs?

**Comment by YuraLukashik** [comment]
@ezzatron that began to happen after upgrade to Symfony 3. The handler is symfony debug error handler https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Debug/ErrorHandler.php#L368 and i think they updated it's interface.

**Comment by YuraLukashik** [comment]
screen shot 2016-12-07 at 15 23 46

**Comment by YuraLukashik** [comment]
@ezzatron it seems that i just had no errors before :)

**Comment by YuraLukashik** [comment]
this bug is reproducible only in php < 7, because php 7.* has Throwable interface which catches such errors.

**Comment by YuraLukashik** [comment]
@ezzatron added test, but it's for specific php versions.

**Comment by ezzatron** [comment]
@YuraLukashik Thanks, that helps a lot!

**Comment by ezzatron** [comment]
@YuraLukashik After looking through Symfony 3's error handler, it seems like they're using even more arguments than the 5 standard ones. I think, based upon that, it's probably wise just to pass on ALL arguments received by the handler. This way we are as transparent as possible.

I've created a branch with your commits plus some changes and more tests on the [error-handler-signature](https://github.com/peridot-php/peridot/tree/error-handler-signature) branch. If you'd like to try this branch, you can do so using this version constraint:

```json
{
    "peridot-php/peridot": "dev-error-handler-signature"
}
```

Is there any chance you could try this branch and let me know if you have any further issues?

Also, just wondering about this statement:

> this bug is reproducible only in php < 7, because php 7.* has Throwable interface which catches such errors.

It seems to me like this has nothing to do with PHP 7, but if I'm missing something, perhaps you could explain this a bit more? In any case, I was able to remove the version restrictions from the spec you wrote, and with some minor adjustments, it passes just fine in all versions of PHP and HHVM.

**Comment by ezzatron** [comment]
Manually merged in [88d93d8](https://github.com/peridot-php/peridot/commit/88d93d8).

**Comment by ezzatron** [comment]
@YuraLukashik This PR is scheduled for release at the end of this week, if you have any more comments or questions, it would be good to address them before then. Cheers!

**Comment by ezzatron** [comment]
Released in [1.19.0](https://github.com/peridot-php/peridot/releases/1.19.0) 🎉

**Comment by YuraLukashik** [comment]
@ezzatron thank you! 🎉

**Pull request closed without merging**
