### PR TITLE
Updated dependencies, PHP>=7.1

### PR DESCRIPTION
**Pull request by Radiergummi**
Hey there!
Since I'm a big fan of testing with peridot, I can't help but notice there weren't that many updates as of late. I need Symfony Console >v4 in some of my projects, but can't, since Peridot still requires the v2.  
Hence I'd like to propose updating all dependencies to more recent versions, as well as raising the PHP version requirement to >= 7.1. 

I know, that shuns backwards compatibility. However, the definite EOL of PHP 5.6 is just ahead (Dec. 31st I think), so I'd say it's definitely okay to cut loose ends, too. Maybe in the shape of a new major version?

Let me know what you think.

*Forgot to mention it - I ran the full test suite, which is all green with some minor modifications.*

### CODE REVIEW

**Comment by andyvanee** [comment]
I'd like to second this. I also ran into this issue, since Composer itself will install Symfony Console v4 on PHP 7. I have created a fork with a more minimal change set, ~~but it's not ideal since it requires installation using the `--ignore-platform-reqs` flag with composer~~ (I've since discovered that the flag is not required after installing from the remote).

https://github.com/andyvanee/peridot/commit/25b056a92503f944c591daf0ce5f6b340b6dc08c

**Comment by Radiergummi** [comment]
@andyvanee thank you for your consideration! I personally feel there's no real reason to test 5.6 applications anymore, but that's just opinion, keeping it in won't hurt.

**Comment by boboudreau** [comment]
The future is now https://www.php.net/supported-versions.php 😄 

I'd agree that adding updated PHP requirements would require a new major version.

**Comment by brianium** [comment]
Hey @boboudreau! @ragboyjr are you still there? thoughts?

**Comment by austinsmorris** [comment]
OOOOOOooooooooOOOOOOOOOOoooooooo

**Comment by ragboyjr** [comment]
hey guys, somehow this missed my radar. Let me take a look :)

**Comment by ragboyjr** [comment]
@Radiergummi Great work, thank you very much, can you rebase/squash, and I'll get this merged?

**Comment by Radiergummi** [comment]
Hey @ragboyjr I'm on vacation currently and don't have my laptop with me, but I'm gonna be back in two weeks. Either that or just drop my PR, fine with me too :)

**Comment by boboudreau** [comment]
Hey all - so are we just waiting on this PR to be squashed into a single commit? It's been a while since I worked in Github, but I thought there's a way to squash on merge? Or are there changes that aren't in this PR that need to be included?

**Comment by austinsmorris** [comment]
> Hey all - so are we just waiting on this PR to be squashed into a single commit? It's been a while since I worked in Github, but I thought there's a way to squash on merge? Or are there changes that aren't in this PR that need to be included?

OOOOOOooooooooOOOOOOOOOOoooooooo

**Comment by boboudreau** [comment]
@Radiergummi @ragboyjr thoughts on merging to get this framework up to date?

**Comment by austinsmorris** [comment]
@boboudreau, plz consider using PHP 6.0

**Comment by mrkrstphr** [comment]
I love how much you care about getting this framework up to date, @boboudreau.

**Comment by ragboyjr** [comment]
@Radiergummi thanks for this, i'll have to think about whether we can release this as 1.20 or if this should wait for a 2.0 release.

**Pull request merged**
